### PR TITLE
Fix Foreman legacy UI erroring out

### LINKED ISSUE #90: undefined method `host_monitoring_result_icon_class' for #<ActionView::Base:0x000000001698d8> Did you mean? host_config_reports_url
Moving this from foreman issue tracking by reqeust:

When we navigate from the monitor > Dashboard > and click on any of our "new hosts" we are getting the error in the subject line.

Here is the section of the foreman rake error log to show whats coming up for us. This is a fresh install and at this point all we're doing is testing deployments and everything seems to deploy fine but we were just curious what might be causing this error so we can fix it.

2023-03-22T12:07:25 [I|app|8f1fa823] Started GET "/hosts/tmr2-fmtest.uanet.edu" for xx.xx.xx.xx at 2023-03-22 12:07:25 -0400
2023-03-22T12:07:25 [I|app|8f1fa823] Processing by HostsController#show as HTML
2023-03-22T12:07:25 [I|app|8f1fa823] Parameters: {"id"=>"sanitizednodename.domain.com"}
2023-03-22T12:07:26 [I|app|8f1fa823] Rendered hosts/show.html.erb within layouts/application (Duration: 209.0ms | Allocations: 52469)
2023-03-22T12:07:26 [I|app|8f1fa823] Rendered layout layouts/application.html.erb (Duration: 209.2ms | Allocations: 52524)
2023-03-22T12:07:26 [W|app|8f1fa823] undefined method `host_monitoring_result_icon_class' for #<ActionView::Base:0x000000001698d8>
8f1fa823 | Did you mean? host_config_reports_url
2023-03-22T12:07:26 [I|app|8f1fa823] Backtrace for 'undefined method `host_monitoring_result_icon_class' for #<ActionView::Base:0x000000001698d8>
8f1fa823 | Did you mean? host_config_reports_url' error (ActionView::Template::Error): undefined method `host_monitoring_result_icon_class' for #<ActionView::Base:0x000000001698d8>
8f1fa823 | Did you mean? host_config_reports_url

We are currently on version 3.5.1

Thanks and let me know if you need any other information.

### PR DESCRIPTION
**Pull request by ananace**
Fixes #90

### CODE REVIEW

**Comment by ekohl** [comment]
In https://github.com/theforeman/foreman_monitoring/pull/94 I'm adding it to the modern UI instead, but it's still lacking actions.

**Comment by laugmanuel** [comment]
I would support fixing this as long as modern UI is not implemented. This seems to be a quick fix for now.

**Comment by ekohl** [comment]
There's a merge conflict, so please rebase.

**Comment by laugmanuel** [comment]
@dgoetz do you mind having a look? I would also purpose a new release after that because the current plugin version is broken on multiple parts. I could take care of packaging PRs

File: app/helpers/foreman_monitoring/hosts_helper.rb [hunk 1]
```diff
@@ -0,0 +1,73 @@
+# frozen_string_literal: true
+
+module ForemanMonitoring
+  module HostsHelper
+    def monitoring_hosts_multiple_actions
+      actions = []
+      actions << { action: [_('Set downtime'), select_multiple_downtime_hosts_path], priority: 1000 } \
+        if authorized_for(:controller => :hosts, :action => :select_multiple_downtime)
+      actions << { action: [_('Change Monitoring Proxy'), select_multiple_monitoring_proxy_hosts_path], priority: 1000 } \
+        if authorized_for(:controller => :hosts, :action => :select_multiple_monitoring_proxy)
```
Comment (ekohl) [inline app/helpers/foreman_monitoring/hosts_helper.rb:10]: Style wise I'd prefer to avoid such long lines
```suggestion
      if authorized_for(:controller => :hosts, :action => :select_multiple_downtime)
        actions << { action: [_('Set downtime'), select_multiple_downtime_hosts_path], priority: 1000 }
      end
      if authorized_for(:controller => :hosts, :action => :select_multiple_monitoring_proxy)
        actions << { action: [_('Change Monitoring Proxy'), select_multiple_monitoring_proxy_hosts_path], priority: 1000 }
      end
        
```

Comment (timogoebel) [reply app/helpers/foreman_monitoring/hosts_helper.rb:10]: Rubocop seems to prefer this kind. I'll commit the original version for now, we can improve the styling in a separate PR.

**Comment by timogoebel** [comment]
Thanks, @ananace.
